version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1337:1337
    volumes:
     - .:/app

  mongodb:
    image: mongo:4
    ports:
      - 27017:27017
